/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as AuthenticatedPlatformStaffRouteImport } from './routes/_authenticated/_platformStaff'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/app/home'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'
import { Route as AuthenticatedPlatformStaffAdminIndexRouteImport } from './routes/_authenticated/_platformStaff/admin/index'
import { Route as AuthenticatedPlatformStaffAdminTontinesRouteImport } from './routes/_authenticated/_platformStaff/admin/tontines'
import { Route as AuthenticatedPlatformStaffAdminUsersRouteImport } from './routes/_authenticated/_platformStaff/admin/users'
import { Route as AuthenticatedAppTontinesTontineIdRouteImport } from './routes/_authenticated/app/tontines/$tontineId'
import { Route as AuthenticatedAppTontinesNewRouteImport } from './routes/_authenticated/app/tontines/new'
import { Route as AuthenticatedAppTontinesTontineIdAdminRouteImport } from './routes/_authenticated/app/tontines/$tontineId/_admin'
import { Route as AuthenticatedAppTontinesTontineIdContributionsRouteImport } from './routes/_authenticated/app/tontines/$tontineId/contributions'
import { Route as AuthenticatedAppTontinesTontineIdCyclesRouteImport } from './routes/_authenticated/app/tontines/$tontineId/cycles'
import { Route as AuthenticatedAppTontinesTontineIdMembersRouteImport } from './routes/_authenticated/app/tontines/$tontineId/members'
import { Route as AuthenticatedAppTontinesTontineIdOverviewRouteImport } from './routes/_authenticated/app/tontines/$tontineId/overview'
import { Route as AuthenticatedAppTontinesTontineIdAdminSettingsRouteImport } from './routes/_authenticated/app/tontines/$tontineId/_admin/settings'
import { Route as AuthenticatedAppTontinesTontineIdAdminValidationRouteImport } from './routes/_authenticated/app/tontines/$tontineId/_admin/validation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformStaffRoute =
  AuthenticatedPlatformStaffRouteImport.update({
    id: '/_platformStaff',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedPlatformStaffAdminIndexRoute =
  AuthenticatedPlatformStaffAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedPlatformStaffRoute,
  } as any)
const AuthenticatedPlatformStaffAdminTontinesRoute =
  AuthenticatedPlatformStaffAdminTontinesRouteImport.update({
    id: '/admin/tontines',
    path: '/admin/tontines',
    getParentRoute: () => AuthenticatedPlatformStaffRoute,
  } as any)
const AuthenticatedPlatformStaffAdminUsersRoute =
  AuthenticatedPlatformStaffAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedPlatformStaffRoute,
  } as any)
const AuthenticatedAppTontinesTontineIdRoute =
  AuthenticatedAppTontinesTontineIdRouteImport.update({
    id: '/tontines/$tontineId',
    path: '/tontines/$tontineId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTontinesNewRoute =
  AuthenticatedAppTontinesNewRouteImport.update({
    id: '/tontines/new',
    path: '/tontines/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTontinesTontineIdAdminRoute =
  AuthenticatedAppTontinesTontineIdAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => AuthenticatedAppTontinesTontineIdRoute,
  } as any)
const AuthenticatedAppTontinesTontineIdContributionsRoute =
  AuthenticatedAppTontinesTontineIdContributionsRouteImport.update({
    id: '/contributions',
    path: '/contributions',
    getParentRoute: () => AuthenticatedAppTontinesTontineIdRoute,
  } as any)
const AuthenticatedAppTontinesTontineIdCyclesRoute =
  AuthenticatedAppTontinesTontineIdCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => AuthenticatedAppTontinesTontineIdRoute,
  } as any)
const AuthenticatedAppTontinesTontineIdMembersRoute =
  AuthenticatedAppTontinesTontineIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAppTontinesTontineIdRoute,
  } as any)
const AuthenticatedAppTontinesTontineIdOverviewRoute =
  AuthenticatedAppTontinesTontineIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAppTontinesTontineIdRoute,
  } as any)
const AuthenticatedAppTontinesTontineIdAdminSettingsRoute =
  AuthenticatedAppTontinesTontineIdAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppTontinesTontineIdAdminRoute,
  } as any)
const AuthenticatedAppTontinesTontineIdAdminValidationRoute =
  AuthenticatedAppTontinesTontineIdAdminValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => AuthenticatedAppTontinesTontineIdAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/style-guide': typeof StyleGuideRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/home': typeof AuthenticatedAppHomeRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/admin/tontines': typeof AuthenticatedPlatformStaffAdminTontinesRoute
  '/admin/users': typeof AuthenticatedPlatformStaffAdminUsersRoute
  '/app/tontines/$tontineId': typeof AuthenticatedAppTontinesTontineIdRouteWithChildren
  '/app/tontines/new': typeof AuthenticatedAppTontinesNewRoute
  '/admin/': typeof AuthenticatedPlatformStaffAdminIndexRoute
  '/app/tontines/$tontineId/contributions': typeof AuthenticatedAppTontinesTontineIdContributionsRoute
  '/app/tontines/$tontineId/cycles': typeof AuthenticatedAppTontinesTontineIdCyclesRoute
  '/app/tontines/$tontineId/members': typeof AuthenticatedAppTontinesTontineIdMembersRoute
  '/app/tontines/$tontineId/overview': typeof AuthenticatedAppTontinesTontineIdOverviewRoute
  '/app/tontines/$tontineId/settings': typeof AuthenticatedAppTontinesTontineIdAdminSettingsRoute
  '/app/tontines/$tontineId/validation': typeof AuthenticatedAppTontinesTontineIdAdminValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/style-guide': typeof StyleGuideRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/home': typeof AuthenticatedAppHomeRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/admin/tontines': typeof AuthenticatedPlatformStaffAdminTontinesRoute
  '/admin/users': typeof AuthenticatedPlatformStaffAdminUsersRoute
  '/app/tontines/$tontineId': typeof AuthenticatedAppTontinesTontineIdRouteWithChildren
  '/app/tontines/new': typeof AuthenticatedAppTontinesNewRoute
  '/admin': typeof AuthenticatedPlatformStaffAdminIndexRoute
  '/app/tontines/$tontineId/contributions': typeof AuthenticatedAppTontinesTontineIdContributionsRoute
  '/app/tontines/$tontineId/cycles': typeof AuthenticatedAppTontinesTontineIdCyclesRoute
  '/app/tontines/$tontineId/members': typeof AuthenticatedAppTontinesTontineIdMembersRoute
  '/app/tontines/$tontineId/overview': typeof AuthenticatedAppTontinesTontineIdOverviewRoute
  '/app/tontines/$tontineId/settings': typeof AuthenticatedAppTontinesTontineIdAdminSettingsRoute
  '/app/tontines/$tontineId/validation': typeof AuthenticatedAppTontinesTontineIdAdminValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/style-guide': typeof StyleGuideRoute
  '/_authenticated/_platformStaff': typeof AuthenticatedPlatformStaffRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/_platformStaff/admin/tontines': typeof AuthenticatedPlatformStaffAdminTontinesRoute
  '/_authenticated/_platformStaff/admin/users': typeof AuthenticatedPlatformStaffAdminUsersRoute
  '/_authenticated/app/tontines/$tontineId': typeof AuthenticatedAppTontinesTontineIdRouteWithChildren
  '/_authenticated/app/tontines/new': typeof AuthenticatedAppTontinesNewRoute
  '/_authenticated/_platformStaff/admin/': typeof AuthenticatedPlatformStaffAdminIndexRoute
  '/_authenticated/app/tontines/$tontineId/_admin': typeof AuthenticatedAppTontinesTontineIdAdminRouteWithChildren
  '/_authenticated/app/tontines/$tontineId/contributions': typeof AuthenticatedAppTontinesTontineIdContributionsRoute
  '/_authenticated/app/tontines/$tontineId/cycles': typeof AuthenticatedAppTontinesTontineIdCyclesRoute
  '/_authenticated/app/tontines/$tontineId/members': typeof AuthenticatedAppTontinesTontineIdMembersRoute
  '/_authenticated/app/tontines/$tontineId/overview': typeof AuthenticatedAppTontinesTontineIdOverviewRoute
  '/_authenticated/app/tontines/$tontineId/_admin/settings': typeof AuthenticatedAppTontinesTontineIdAdminSettingsRoute
  '/_authenticated/app/tontines/$tontineId/_admin/validation': typeof AuthenticatedAppTontinesTontineIdAdminValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/style-guide'
    | '/app'
    | '/app/home'
    | '/app/profile'
    | '/admin/tontines'
    | '/admin/users'
    | '/app/tontines/$tontineId'
    | '/app/tontines/new'
    | '/admin/'
    | '/app/tontines/$tontineId/contributions'
    | '/app/tontines/$tontineId/cycles'
    | '/app/tontines/$tontineId/members'
    | '/app/tontines/$tontineId/overview'
    | '/app/tontines/$tontineId/settings'
    | '/app/tontines/$tontineId/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/style-guide'
    | '/app'
    | '/app/home'
    | '/app/profile'
    | '/admin/tontines'
    | '/admin/users'
    | '/app/tontines/$tontineId'
    | '/app/tontines/new'
    | '/admin'
    | '/app/tontines/$tontineId/contributions'
    | '/app/tontines/$tontineId/cycles'
    | '/app/tontines/$tontineId/members'
    | '/app/tontines/$tontineId/overview'
    | '/app/tontines/$tontineId/settings'
    | '/app/tontines/$tontineId/validation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/style-guide'
    | '/_authenticated/_platformStaff'
    | '/_authenticated/app'
    | '/_authenticated/app/home'
    | '/_authenticated/app/profile'
    | '/_authenticated/_platformStaff/admin/tontines'
    | '/_authenticated/_platformStaff/admin/users'
    | '/_authenticated/app/tontines/$tontineId'
    | '/_authenticated/app/tontines/new'
    | '/_authenticated/_platformStaff/admin/'
    | '/_authenticated/app/tontines/$tontineId/_admin'
    | '/_authenticated/app/tontines/$tontineId/contributions'
    | '/_authenticated/app/tontines/$tontineId/cycles'
    | '/_authenticated/app/tontines/$tontineId/members'
    | '/_authenticated/app/tontines/$tontineId/overview'
    | '/_authenticated/app/tontines/$tontineId/_admin/settings'
    | '/_authenticated/app/tontines/$tontineId/_admin/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StyleGuideRoute: typeof StyleGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_platformStaff': {
      id: '/_authenticated/_platformStaff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPlatformStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/home': {
      id: '/_authenticated/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_platformStaff/admin/': {
      id: '/_authenticated/_platformStaff/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedPlatformStaffAdminIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformStaffRoute
    }
    '/_authenticated/_platformStaff/admin/tontines': {
      id: '/_authenticated/_platformStaff/admin/tontines'
      path: '/admin/tontines'
      fullPath: '/admin/tontines'
      preLoaderRoute: typeof AuthenticatedPlatformStaffAdminTontinesRouteImport
      parentRoute: typeof AuthenticatedPlatformStaffRoute
    }
    '/_authenticated/_platformStaff/admin/users': {
      id: '/_authenticated/_platformStaff/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedPlatformStaffAdminUsersRouteImport
      parentRoute: typeof AuthenticatedPlatformStaffRoute
    }
    '/_authenticated/app/tontines/$tontineId': {
      id: '/_authenticated/app/tontines/$tontineId'
      path: '/tontines/$tontineId'
      fullPath: '/app/tontines/$tontineId'
      preLoaderRoute: typeof AuthenticatedAppTontinesTontineIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tontines/new': {
      id: '/_authenticated/app/tontines/new'
      path: '/tontines/new'
      fullPath: '/app/tontines/new'
      preLoaderRoute: typeof AuthenticatedAppTontinesNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tontines/$tontineId/_admin': {
      id: '/_authenticated/app/tontines/$tontineId/_admin'
      path: ''
      fullPath: '/app/tontines/$tontineId'
      preLoaderRoute: typeof AuthenticatedAppTontinesTontineIdAdminRouteImport
      parentRoute: typeof AuthenticatedAppTontinesTontineIdRoute
    }
    '/_authenticated/app/tontines/$tontineId/contributions': {
      id: '/_authenticated/app/tontines/$tontineId/contributions'
      path: '/contributions'
      fullPath: '/app/tontines/$tontineId/contributions'
      preLoaderRoute: typeof AuthenticatedAppTontinesTontineIdContributionsRouteImport
      parentRoute: typeof AuthenticatedAppTontinesTontineIdRoute
    }
    '/_authenticated/app/tontines/$tontineId/cycles': {
      id: '/_authenticated/app/tontines/$tontineId/cycles'
      path: '/cycles'
      fullPath: '/app/tontines/$tontineId/cycles'
      preLoaderRoute: typeof AuthenticatedAppTontinesTontineIdCyclesRouteImport
      parentRoute: typeof AuthenticatedAppTontinesTontineIdRoute
    }
    '/_authenticated/app/tontines/$tontineId/members': {
      id: '/_authenticated/app/tontines/$tontineId/members'
      path: '/members'
      fullPath: '/app/tontines/$tontineId/members'
      preLoaderRoute: typeof AuthenticatedAppTontinesTontineIdMembersRouteImport
      parentRoute: typeof AuthenticatedAppTontinesTontineIdRoute
    }
    '/_authenticated/app/tontines/$tontineId/overview': {
      id: '/_authenticated/app/tontines/$tontineId/overview'
      path: '/overview'
      fullPath: '/app/tontines/$tontineId/overview'
      preLoaderRoute: typeof AuthenticatedAppTontinesTontineIdOverviewRouteImport
      parentRoute: typeof AuthenticatedAppTontinesTontineIdRoute
    }
    '/_authenticated/app/tontines/$tontineId/_admin/settings': {
      id: '/_authenticated/app/tontines/$tontineId/_admin/settings'
      path: '/settings'
      fullPath: '/app/tontines/$tontineId/settings'
      preLoaderRoute: typeof AuthenticatedAppTontinesTontineIdAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAppTontinesTontineIdAdminRoute
    }
    '/_authenticated/app/tontines/$tontineId/_admin/validation': {
      id: '/_authenticated/app/tontines/$tontineId/_admin/validation'
      path: '/validation'
      fullPath: '/app/tontines/$tontineId/validation'
      preLoaderRoute: typeof AuthenticatedAppTontinesTontineIdAdminValidationRouteImport
      parentRoute: typeof AuthenticatedAppTontinesTontineIdAdminRoute
    }
  }
}

interface AuthenticatedPlatformStaffRouteChildren {
  AuthenticatedPlatformStaffAdminTontinesRoute: typeof AuthenticatedPlatformStaffAdminTontinesRoute
  AuthenticatedPlatformStaffAdminUsersRoute: typeof AuthenticatedPlatformStaffAdminUsersRoute
  AuthenticatedPlatformStaffAdminIndexRoute: typeof AuthenticatedPlatformStaffAdminIndexRoute
}

const AuthenticatedPlatformStaffRouteChildren: AuthenticatedPlatformStaffRouteChildren =
  {
    AuthenticatedPlatformStaffAdminTontinesRoute:
      AuthenticatedPlatformStaffAdminTontinesRoute,
    AuthenticatedPlatformStaffAdminUsersRoute:
      AuthenticatedPlatformStaffAdminUsersRoute,
    AuthenticatedPlatformStaffAdminIndexRoute:
      AuthenticatedPlatformStaffAdminIndexRoute,
  }

const AuthenticatedPlatformStaffRouteWithChildren =
  AuthenticatedPlatformStaffRoute._addFileChildren(
    AuthenticatedPlatformStaffRouteChildren,
  )

interface AuthenticatedAppTontinesTontineIdAdminRouteChildren {
  AuthenticatedAppTontinesTontineIdAdminSettingsRoute: typeof AuthenticatedAppTontinesTontineIdAdminSettingsRoute
  AuthenticatedAppTontinesTontineIdAdminValidationRoute: typeof AuthenticatedAppTontinesTontineIdAdminValidationRoute
}

const AuthenticatedAppTontinesTontineIdAdminRouteChildren: AuthenticatedAppTontinesTontineIdAdminRouteChildren =
  {
    AuthenticatedAppTontinesTontineIdAdminSettingsRoute:
      AuthenticatedAppTontinesTontineIdAdminSettingsRoute,
    AuthenticatedAppTontinesTontineIdAdminValidationRoute:
      AuthenticatedAppTontinesTontineIdAdminValidationRoute,
  }

const AuthenticatedAppTontinesTontineIdAdminRouteWithChildren =
  AuthenticatedAppTontinesTontineIdAdminRoute._addFileChildren(
    AuthenticatedAppTontinesTontineIdAdminRouteChildren,
  )

interface AuthenticatedAppTontinesTontineIdRouteChildren {
  AuthenticatedAppTontinesTontineIdAdminRoute: typeof AuthenticatedAppTontinesTontineIdAdminRouteWithChildren
  AuthenticatedAppTontinesTontineIdContributionsRoute: typeof AuthenticatedAppTontinesTontineIdContributionsRoute
  AuthenticatedAppTontinesTontineIdCyclesRoute: typeof AuthenticatedAppTontinesTontineIdCyclesRoute
  AuthenticatedAppTontinesTontineIdMembersRoute: typeof AuthenticatedAppTontinesTontineIdMembersRoute
  AuthenticatedAppTontinesTontineIdOverviewRoute: typeof AuthenticatedAppTontinesTontineIdOverviewRoute
}

const AuthenticatedAppTontinesTontineIdRouteChildren: AuthenticatedAppTontinesTontineIdRouteChildren =
  {
    AuthenticatedAppTontinesTontineIdAdminRoute:
      AuthenticatedAppTontinesTontineIdAdminRouteWithChildren,
    AuthenticatedAppTontinesTontineIdContributionsRoute:
      AuthenticatedAppTontinesTontineIdContributionsRoute,
    AuthenticatedAppTontinesTontineIdCyclesRoute:
      AuthenticatedAppTontinesTontineIdCyclesRoute,
    AuthenticatedAppTontinesTontineIdMembersRoute:
      AuthenticatedAppTontinesTontineIdMembersRoute,
    AuthenticatedAppTontinesTontineIdOverviewRoute:
      AuthenticatedAppTontinesTontineIdOverviewRoute,
  }

const AuthenticatedAppTontinesTontineIdRouteWithChildren =
  AuthenticatedAppTontinesTontineIdRoute._addFileChildren(
    AuthenticatedAppTontinesTontineIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppTontinesTontineIdRoute: typeof AuthenticatedAppTontinesTontineIdRouteWithChildren
  AuthenticatedAppTontinesNewRoute: typeof AuthenticatedAppTontinesNewRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppTontinesTontineIdRoute:
    AuthenticatedAppTontinesTontineIdRouteWithChildren,
  AuthenticatedAppTontinesNewRoute: AuthenticatedAppTontinesNewRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPlatformStaffRoute: typeof AuthenticatedPlatformStaffRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPlatformStaffRoute: AuthenticatedPlatformStaffRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StyleGuideRoute: StyleGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
